### ISSUE TITLE
Kottans philosophy

### ISSUE THREAD

**Issue by zonzujiro** [kottans/library#2]
https://onedrive.live.com/edit.aspx?resid=28743F1E9F87C4F1!66922&ithint=file%2cdocx&authkey=!AEP79t2xaEZlWvk

Looking for your opinion @OleksiyRudenko @suchov @AMashoshyna

**Comment by OleksiyRudenko** [comment]
@zonzujiro thank you for compiling this up.

UKR and ENG versions LGTM. Just added a single suggestion as a comment (didn't find Suggesting mode under Review tab).
RUS seems to be a pretty much different. How about putting the "paper" in landscape orientation and putting all three versions in a table of 3 columns, 1 cell per paragraph?
This might help keeping all translations in sync better compared to scroll up/down strategy.
What do you think?

**Comment by zonzujiro** [comment]
@OleksiyRudenko my bad, I have not provided description for this document.

So, Russian version:
During my work on a new website I understood, that when we need text for articles, websites, etc. with clear description of what Kottans are, we all have slightly different view of what our community is and how it works. And such description raises even more questions. As an example, who are we? Just free courses? But we have not only courses. A platform? But what does it mean? Why free? Who can be part of community? 
Because of this, we all use different wordings from time to time. We all live with differences without a problem because we operate in the context of our community. But for someone who is outside of it, simple description which can be used for understanding of our ideas becomes mostly unreachable.
So I made this Russian (because Russian is my native language) text which I threat as our internal document and which can be used as source of ideas or concrete copy-pasting of text. Because of this I believe that it is not requires translation right now.
But ff you have another opinion - fill free to share it. It will be interesting for me to hear it and discuss it.

As examples of texts, which was made using this long text, are texts which was made by our outstaff marketolog Angelina. They can be used everywhere and will be used on our new site, which I hope we will finish eventually.

**Comment by suchov** [comment]
The only thing - probably we can change 7 years to 8 years already.
