### ISSUE TITLE
Collect all materials in this repo

### ISSUE THREAD

**Issue by zonzujiro** [kottans/library#5]
What do you think about creation of one monorepo with our materials, FAQ and else?

Right now we can merge this repo in `library`:

1. https://github.com/kottans/kottans-course-bootstrap
2. https://github.com/kottans/artifacts
3. https://github.com/kottans/endorsements

Those repos can be deleted and we will have one repo with all our staff.

Also, some texts should be created as Wiki, not like `.md` files. As an example code review guides.

@OleksiyRudenko should we place our materials about conference here? Guides, Call for Papers, etc.

@suchov @AMashoshyna

**Comment by AMashoshyna** [comment]
Nice idea! Maybe even gitbook for longer texts or something fancy

**Comment by suchov** [comment]
Yeh, I think getting in all together is a gerat idea!

**Comment by OleksiyRudenko** [comment]
Sounds good. We might then refer to wiki pages in this repo from other repos. E.g. `frontend` might refer to HTAQ page and homeworks repos to Code Review Guidelines.

My only concern is that if we change the wiki pages structure will links in other repos still be valid? Maintaining links consistency across multiple repos might be a pain.

**Comment by zonzujiro** [comment]
@OleksiyRudenko all I can propose is not change structure of our wiki.

This issue can be good platform for discussion about it?

**Comment by OleksiyRudenko** [comment]
While experimenting with wiki made the engine screaming ))
![image](https://user-images.githubusercontent.com/8686631/68233128-3d36e400-0007-11ea-885c-57f2e832ced5.png)

**Comment by OleksiyRudenko** [comment]
OK. After some research I found that we can keep real file structure flat and bring some nested structure customizing the side bar only.

Example: https://github.com/OleksiyRudenko/test-repo/wiki (clickable controls is actually embedded HTML, not a built-in wiki engine feature)

What is important to keep links persistent:
1. Do not rename pages as links get auto-generated from page title
1. Do not move pages across directories in internal wiki representation (It is actually possible to organize files across sub-directories when working with a wiki as a repo)

Some pages can be "hidden", i.e. not exposed in custom sidebar.

So, we can agree on certain structure and start wikiing.

**Comment by OleksiyRudenko** [comment]
Yet another option to consider is that a repo with cross-linked `.md` files can be published on github pages in a couple of clicks with an easy-to-setup Jekyll theming.

**Comment by zonzujiro** [comment]
Great job with example. Thank you!

> So, we can agree on certain structure and start wikiing.

Contributing into wiki doesn't requires PR, so anyone can write anything. 
Should we discuss list of material first?

> Yet another option to consider is that a repo with cross-linked .md files can be published on github pages in a couple of clicks with an easy-to-setup Jekyll theming.

I haven't planned anything like this. For what purpose?

**Comment by OleksiyRudenko** [comment]
> > So, we can agree on certain structure and start wikiing.

> Contributing into wiki doesn't requires PR, so anyone can write anything.

Well, repo maintainers only anyway.

> Should we discuss list of material first?

I would suggest aligning the contents.

> > Yet another option to consider is that a repo with cross-linked .md files can be published on github pages in a couple of clicks with an easy-to-setup Jekyll theming.

> I haven't planned anything like this. For what purpose?

It was just a proposal to consider this option.

**Comment by zonzujiro** [comment]
To be cooler, we can run https://docusaurus.io/ over MD files to generate the documentation website (the same way is used by create-react-app, jest, reason). 

What you think?

**Comment by AMashoshyna** [comment]
@Croftyland  a call for docusaurus-hero  ^ (if you have time and resources, of course)

**Comment by Croftyland** [comment]
Can be done easily

**Comment by zonzujiro** [comment]
So we need:

1. CoC - https://github.com/kottans/library/issues/1
2. [Course bootstrap](https://github.com/kottans/kottans-course-bootstrap) - https://github.com/kottans/library/issues/3
3. Meetup/conference bootstrap - @Croftyland what you think on this matter?
4. Code review guides

What else?

**Comment by Croftyland** [comment]
I was talking with @AMashoshyna about making blog with translating books, writing articles ect.

This site is perfectly matches what I want and how I see it:
https://reactresources.com/conferences

**Comment by AMashoshyna** [comment]
FAQ maybe? Or link to FAQ elsewhere.

**Comment by Croftyland** [comment]
Collected FAQ or section for it?

**Comment by AMashoshyna** [comment]
Maybe also links to learning materials/other content created for Kottans courses, like Git course by @OleksiyRudenko. I believe we had other workshops and useful things, would be nice to have all of them in a catalog

**Comment by Croftyland** [comment]
@AMashoshyna have you seen [link](https://reactresources.com/conferences) ?)

**Comment by AMashoshyna** [comment]
@Croftyland to Git course? This one? https://github.com/kottans/git-course

**Comment by Croftyland** [comment]
So, for summing up, I have [collected](https://github.com/Croftyland/junior) all repo, videos, and links which have mentioned @zonzujiro 

If there are any other ideas about how to fill content in this docu, fill free to write
